### PR TITLE
replace joi validation with JSON Schema and Ajv

### PR DESCRIPTION
**Pull request by stipsan**
Opening the PR now so we can have the discussion here:

1. The URL filtering is a bit fuzzy. If we use `forma: url | uri | uri-reference` it breaks backwards compatibility with how our manifests use relative urls today, and some sanity tests that prevent stuff like weird non-http protocols.

2. There are only two tests that fail. Podium v3 removes trailing whitespace on `manifest.name` and `manifest.version`. I've failed to find a way to specify that behavior in JSON Schema.

3. Ajv validates the whole schema. While podium-lib/schemas today exports individual validators for every individual property in the schema that is used in some of our other packages: https://github.com/podium-lib/client/blob/4d1d0c0b760d44f8d27119e95a6c008c39f83f94/lib/client.js#L118 Ajv don't have a way of validating just a property. Should we work around that?

<details>
<summary>Slack thread</summary>

> @digitalsadhu: for point 2, ajv does validation only and won’t change the values the way joi does?

> @digitalsadhu: I guess for point 1 perhaps hard coding the regex for url is the way to go for now? We could perhaps look at the consequences of refactoring to use url|uri|uri-reference at a later stage?

> @trygve-lie: 3.  I would suggest making util methods (not joi but plain methods) which reflect the same checking as in the schema which we use for input validation in the modules.

> @trygve-lie: 2. I'm fine with the schema just not allowing whitespace. The removing whitespace in that rule is there probably to cater for when the schema is used to validate arguments in the modules. If we make methods for argument validation we can add stripping of those white spaces there. We don't need it in the schema.

> @trygve-lie: 1. Which tests are failing if we use `uri-reference` in the schema?

> @trygve-lie: Another alternative is to use a pattern to check URIs despite that there is no pattern which matches all possible URIs. We probably do not need to match all possible combos in the spec so this one will probably do for absolute URIs: https://tools.ietf.org/html/rfc3986#appendix-B

</details>

Answering a few of the questions that came up on slack:

1. These tests are failing when using `uri-reference`:

   - `manifest.uri - contains illegal URI scheme - should return error`: `gopher://www.finn.no/content`
   - `manifest.content - contains String value - should return error`: `<section>banan</section>`
   - `manifest.fallback - contains String value - should return error`: `<section>banan</section>`

2. It's more of a limitation in JSON Schema than ajv. We can specify what's valid or invalid, but the spec does not attempt to implement type coercion or data sanitizing. Like @trygve-lie says we could implement that outside the schema.

3. I discovered how we could validate just parts of the schema:
```
module.exports.schema = ajv.compile(schema);
module.exports.name = ajv.compile(schema.properties.name);
// With whitespace trimming, ugly but functional example
module.exports.name = (name) => ajv.compile(schema.properties.name)(name).trim();
```

This relates to https://github.com/podium-lib/issues/issues/9

### CODE REVIEW

**Comment by trygve-lie** [comment]
Good work. Though; a couple of things:

The json schema should be a json file which other languages than javascript can consume. We want this to be a source file a potential Java, Go, whatever implementation can use. In other words, we can not do this in the schema:

```js
const { uriFormat } = require('./utils');

[ ... snip ... ]

proxy: {
    type: 'object',
    default: {},
    maxProperties: 4,
    patternProperties: { '.*': uriFormat },
},
```

I also would like to completely remove `joi`. So I think we need to somewhat get a uri regex which cover our need without depending on `joi`.

**Comment by stipsan** [comment]
@trygve-lie @digitalsadhu @alexanbj I have another question:

4. I notice we are still exporting `hostOptionsSchema` for compatibility with Podium v1, do we want to keep doing that with the `manifest` export that uses Joi? https://github.com/podium-lib/schemas/blob/a675f427263bf0123e6d015b0761a5affb805fed/lib/index.js#L11-L12 or should we remove it so we can drop the Joi dependency entirely, but the cost being no backwards compatibility?

**Comment by stipsan** [comment]
Ah for some reason I didn't get a notification about your feedback @trygve-lie.
I just pushed a change that generates a static manifest.json file on prepublishOnly, what do you think?

I don't see a problem with a static json approach though, the only detail there is we'd need to keep the regex pattern in sync in two locations: in the json, and in the utils file.

**Comment by trygve-lie** [comment]
lgtm :100:

**Pull request merged**
